apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: waste
    secureJsonData:
      password: waste-dev-password
    jsonData:
      database: waste
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    isDefault: true

  - name: WastePortalAPI
    type: yesoreyeram-infinity-datasource
    jsonData:
      base_url: http://backend-api:8000
    isDefault: false
